apiVersion: v2
name: tailscale-derp
description: Tailscale DERP Relay Server Helm Chart
home: https://github.com/sspreitzer/helm-tailscale/tree/main/charts/tailscale-derp
sources:
  - https://github.com/sspreitzer/helm-tailscale.git
maintainers:
  - name: Sascha Spreitzer
    email: sascha@spreitzer.ch
    url: https://github.com/sspreitzer
icon: https://tailscale.com/files/apple-touch-icon.png
version: 1.44.0
appVersion: 1.44.0
