name: Helm Charts

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      chart:
        description: Helm Chart to Build
        default: 'tailscale-proxy'
        required: true
        type: string

jobs:

  Helm:
    runs-on: ubuntu-latest
    concurrency: Helm
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read VERSION file
        id: getversion
        run: echo "version=$(cat TAILSCALE_VERSION | sed 's|^v||g')" >> $GITHUB_OUTPUT
      - name: Create Cache Directory
        run: mkdir -p cache
      - name: Add Tailscale Helm Repository
        run: helm repo add tailscale https://spreitzer.ch/helm-tailscale
      - name: Load Tailscale Repository Index
        run: helm repo update tailscale
      - name: Pull All Helm Charts
        run: helm search repo tailscale -o json | jq '.[] | .name + " " + .version' -r | awk '{ print "helm pull --destination cache/", $1, "--version", $2; }' | xargs -I {} bash -c "{}"
      - name: Update Helm Chart dependencies
        run: helm dependency update charts/${{ inputs.chart }}
      - name: Build Helm Chart
        run: helm package charts/${{ inputs.chart }} --destination cache --app-version ${{ steps.getversion.outputs.version }}
      - name: Create Helm Repository
        run: helm repo index cache --url https://spreitzer.ch/helm-tailscale
      - name: Create GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: cache
      - name: Deploy Helm Repository on GitHub Pages
        uses: actions/deploy-pages@v1      
